layout_spectrum: 0.179914
color:
  saturation: 0.594522
  brandStrength: 1
  lightness: 0.2795269
  brandColors:
    - '#0E0C0B'
    - '#FFFFFC'
    - '#2F4CCF'
    - '#E1766D'
    - '#66A30D'
  rhythmicContrast: 0.9790547
typography_spectrum: 0.2948442
name: ScottBauer
