name: ScottBauer
favicon: null
layout_spectrum: 0.88642
typography_spectrum: 0.06615
title: "Scott Bauer's Interweb Home"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#dbc792'
    - '#312a18'
    - '#fafafa'
    - '#988f6f'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
